// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uepcuigiegeqefgrpifu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcGN1aWdpZWdlcWVmZ3JwaWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTUyNDQsImV4cCI6MjA3NTc5MTI0NH0.dhbvQWeBctzpaGqwnGuMGy0hP3-bfuHBhZxVxA6-Fv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});